language: cpp

compiler:
  - clang-8
  - gcc-9

install:
  - wget https://github.com/sharkdp/hyperfine/releases/download/v1.6.0/hyperfine_1.6.0_amd64.deb
  - sudo dpkg -i hyperfine_1.6.0_amd64.deb
  - make

script:
  - ./bench